version: "3.9"

services: 
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis
      - db 
    links:
      - db:db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - "80:80"
    depends_on:
      - redis
      - backend

  worker:
    build: .
    container_name: celery-worker
    command: celery -A core worker -l INFO
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  celery-beat:
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./core:/app
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
  
