version: "3.9"

services: 
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery-worker
    command: celery -A core worker -l INFO
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  smtp-server:
    image: mailhog/mailhog
    restart: always
    container_name: mailhog
    logging:
      driver: 'none'  # disable saving logs
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
        - mailhog-data:/mailhog/

volumes:
  mailhog-data: