name: Django Project Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose Setup
      run: docker compose -f docker-compose-stage.yml up -d
    - name: Run tests
      run: docker compose -f docker-compose-stage.yml exec backend sh -c "flake8 && pytest ."

  Deploy:
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: connect and execute commands
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        script: |
          cd ${{secrets.PROJECT_PATH}}
          docker compose -f docker-compose-stage.yml stop
          git pull
          docker compose -f docker-compose-stage.yml restart
